sudo: false

language: node_js

os:
  - linux
  # - osx
  - windows

node_js:
  - 6
  - 7
  - 8

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:

before_script:
  - yarn

script:
  - yarn cover

after_script:
  - yarn add codecov
  - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov
