sudo: false

language: node_js

os:
  - linux
  # - osx
  - windows

node_js:
  - 6
  - 7
  - 8

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - yarn global add nyc codecov

script:
  - yarn cover

after_script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
