sudo: false

os:
  # https://travis-ci.community/t/node-js-build-fails-with-no-obvious-error/961
  # - windows
  - linux
  - osx

language: node_js

node_js:
  - lts/*
  - node

cache:
  yarn: true

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - yarn global add nyc codecov

script:
  - yarn lint
  - yarn coverage

after_script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
