sudo: false

os:
  - osx
  - windows
  - linux

language: node_js

node_js:
  - 8
  - 10

cache:
  yarn: true

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - yarn global add nyc codecov

script:
  - yarn lint
  - yarn coverage

after_script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
